### ISSUE TITLE
Transcripts do not correspond to the correct amino acid change

### ISSUE THREAD

**Issue by gilhornung** [ambj/MuPeXI#4]
Hi,

MuPeXI and VEP files can be found here:
http://incpm-2.weizmann.ac.il/bioinfo/gil/mupexi_bug/

Specifically for the gene  XBP1 ENSG00000100219,
I notice several transcripts in the VEP and the have different amino acid changes:
ENST00000344347 has S/X
ENST00000216037 has Q/X

Nonetheless, they both appear as Q/X in the mupexi file.

All the best,

Gil Hornung

**Comment by ambj** [comment]
Thanks for pointing this out. I believe this affects only frameshift mutations where the amino acid changes differ across splice isoforms. We'll look into this soon.
Best, 
/AM

**Comment by ambj** [comment]
Hi Gil 

The bug is now fixed on the dev branch - sorry for the long wait. 

There where two things: 
1) All transcript names where annotated for the Q/X mutation eventough this only occurred in 3 transcripts 
2) The S/X mutation gave directly rise to a stop codon and therefor the mutation sequence generated where one aa shorter than user defined length - resulting in no relevant peptides. 

The dev branch will be merged with the master branch later this week releasing the new version.

Best, 
/AM
